In [1]:
from google.colab import files
import pandas as pd

In [2]:
uploaded = files.upload()

Saving student.csv to student (1).csv

In [3]:
# Đọc file csv và chuyển thành DataFrame
df = pd.read_csv('student.csv')

# **Các hàm và thuộc tính cơ bản**

In [4]:
# Trả về 5 hàng đầu tiên của Data Frame
df.head()
# df.head(10)

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5

In [5]:
# Cung cấp thông tin tổng quan về Data Frame, bao gồm số lượng hàng, cột, kiểu dữ liệu của từng cột và số giá trị không rỗng
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  307 non-null    int64
 1   name                307 non-null    object
 2   nationality         307 non-null    object
 3   city                307 non-null    object
 4   latitude            307 non-null    float64
 5   longitude           307 non-null    float64
 6   gender              307 non-null    object
 7   ethnic.group        0 non-null      float64
 8   age                 307 non-null    int64
 9   english.grade       307 non-null    float64
 10  math.grade          307 non-null    float64
 11  sciences.grade      307 non-null    float64
 12  language.grade      307 non-null    float64
 13  portfolio.rating    307 non-null    int64
 14  coverletter.rating  307 non-null    float64
 15  refletter.rating    307 non-null    int64
dtypes: float64(8), int64(4), object(4)
memory usage: 38.5+ KB

In [6]:
# Tạo thống kê mô tả (số lượng, trung bình, độ lệch chuẩn, giá trị min/max, phân vị) cho các cột số trong Data Frame
df.describe()

,id,latitude,longitude,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
count,307.000000,307.000000,307.000000,0.0,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000,307.000000
mean,153.000000,32.863388,-64.539121,NaN,21.964169,3.369707,3.414332,3.446580,4.396417,3.986971,4.110749,4.188925
std,88.767487,13.498582,81.249146,NaN,1.248013,0.538724,0.476839,0.509081,0.996474,0.928749,0.823936,0.842193
min,0.000000,-33.450000,-123.130000,NaN,19.000000,1.500000,2.100000,1.400000,1.000000,1.000000,1.000000,1.000000
25%,76.500000,32.720000,-118.240000,NaN,21.000000,3.100000,3.100000,3.200000,4.000000,3.500000,4.000000,4.000000
50%,153.000000,34.390000,-99.140000,NaN,22.000000,3.500000,3.500000,3.600000,5.000000,4.000000,4.000000,4.000000
75%,229.500000,38.960000,-73.855000,NaN,23.000000,3.800000,3.800000,3.800000,5.000000,5.000000,5.000000,5.000000
max,306.000000,59.890000,139.750000,NaN,26.000000,4.000000,4.000000,4.000000,5.000000,5.000000,5.000000,5.000000

In [7]:
# Thuộc tính trả về một tuple biểu thị kích thước của Data Frame (số hàng, số cột)
df.shape

(307, 16)

In [8]:
# Thuộc tính trả về danh sách tên các cột trong Data Frame
df.columns

Index(['id', 'name', 'nationality', 'city', 'latitude', 'longitude', 'gender',
       'ethnic.group', 'age', 'english.grade', 'math.grade', 'sciences.grade',
       'language.grade', 'portfolio.rating', 'coverletter.rating',
       'refletter.rating'],
      dtype='object')

In [9]:
# Thuộc tính trả về kiểu dữ liệu của từng cột
df.dtypes

id                      int64
name                   object
nationality            object
city                   object
latitude              float64
longitude             float64
gender                 object
ethnic.group          float64
age                     int64
english.grade         float64
math.grade            float64
sciences.grade        float64
language.grade        float64
portfolio.rating        int64
coverletter.rating    float64
refletter.rating        int64
dtype: object

# **Truy cập dữ liệu trong Data Frame**

In [10]:
# Truy cập dữ liệu bằng nhãn (label-based)
df.loc[30, 'name'] # Truy cập giá trị hàng 30, cột 'name'

'Dakota Wirth'

In [11]:
# Truy cập dữ liệu bằng chỉ số index (integer-based)
df.iloc[35, 2] # Truy cập giá trị hàng 35, cột 2

'India'

In [12]:
# Truy cập một giá trị đơn bằng nhãn, nhanh hơn .loc[] cho truy cập đơn lẻ
df.at[30, 'name']

'Dakota Wirth'

In [13]:
# Truy cập một giá trị đơn bằng chỉ số index, nhanh hơn .iloc[]
df.iat[35, 2]

'India'

In [14]:
# Lọc các hàng trong Data Frame thỏa mãn điều kiện
df[df['age'] > 25]  # Lọc các hàng có giá trị cột 'age' lớn hơn 25

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating
83,83,Luke Davey,United States of America,Los Angeles,34.05,-118.24,M,NaN,26,3.8,3.4,3.7,5.0,4,5.0,3

# **Thêm, xóa, sửa cột trong Data Frame**

In [15]:
# Tạo cột mới 'average' bằng cách tính giá trị trung bình các cột .grade
df['average'] = (df['english.grade'] + df['math.grade'] + df['sciences.grade']) / 3
df.head()

,id,name,nationality,city,latitude,longitude,gender,ethnic.group,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,average
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,NaN,22,3.5,3.7,3.1,1.0,4,4.0,4,3.433333
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,NaN,22,2.9,3.2,3.6,5.0,5,4.0,5,3.233333
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,NaN,22,3.9,3.8,3.2,5.0,3,3.0,4,3.633333
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,NaN,20,3.3,2.8,3.2,5.0,5,2.0,4,3.100000
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,NaN,21,3.7,2.6,3.4,1.0,4,4.0,5,3.233333

In [16]:
# Xóa cột 'ethnic.group'
df = df.drop(columns=['ethnic.group'])
df.head()

,id,name,nationality,city,latitude,longitude,gender,age,english.grade,math.grade,sciences.grade,language.grade,portfolio.rating,coverletter.rating,refletter.rating,average
0,0,Kiana Lor,China,Suzhou,31.31,120.62,F,22,3.5,3.7,3.1,1.0,4,4.0,4,3.433333
1,1,Joshua Lonaker,United States of America,Santa Clarita,34.39,-118.54,M,22,2.9,3.2,3.6,5.0,5,4.0,5,3.233333
2,2,Dakota Blanco,United States of America,Oakland,37.80,-122.27,F,22,3.9,3.8,3.2,5.0,3,3.0,4,3.633333
3,3,Natasha Yarusso,United States of America,Castro Valley,37.69,-122.09,F,20,3.3,2.8,3.2,5.0,5,2.0,4,3.100000
4,4,Brooke Cazares,Brazil,São José dos Campos,-23.18,-45.88,F,21,3.7,2.6,3.4,1.0,4,4.0,5,3.233333